#############################
###    shared settings    ###
#############################
x-common-settings: &common
  build: 
    context: .  
    dockerfile: Dockerfile
  image: hrcnthu/lerobot-koch-actpp:gpu

  volumes:
    - $HOME/.Xauthority:/root/.Xauthority
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /dev/shm:/dev/shm

    - ../entrypoint:/root/entrypoint
    - ../command:/root/command
    - ../../calibration:/root/calibration
    - ../../lerobot:/root/lerobot
    - ../../ros2-ws:/root/ros2-ws

    ## NOTE: mount .git to setup the git credentials
    #  you can comment out this line, 
    #  if you don't need to upload dataset to huggingface.
    - ../../.git/:/root/.git
  
  environment:
    - DISPLAY=${DISPLAY}
  
  tty: true
  network_mode: host
  privileged: true
  stop_grace_period: 1s
  devices:
    - /dev:/dev


############################
###   shared settings    ###
############################
x-gpu-settings: &gpu
  runtime: nvidia
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    

##############################
###   Container Services   ###
##############################
services:
  raw:
    <<: [*common, *gpu]
    container_name: koch-actpp-raw
      
    entrypoint: []
    command: ["/bin/bash"]


  ws-build:
    <<: [*common, *gpu]
    container_name: koch-actpp-ws-build

    entrypoint: []
    command: ["/root/command/ws-build.sh"]


  arm-cali:
    <<: [*common, *gpu]
    container_name: koch-actpp-arm-cali

    entrypoint: [/root/entrypoint/symlinks.sh"]
    command: ["/root/command/arm-cali.sh"]


  arm-sync:
    <<: [*common, *gpu]
    container_name: koch-actpp-arm-sync

    entrypoint: ["/root/entrypoint/symlinks.sh"]
    command: ["/root/command/arm-sync.sh"]

  
  armv-rec:
    <<: [*common, *gpu]
    container_name: koch-actpp-armv-rec
    
    entrypoint: ["/root/entrypoint/symlinks.sh"]
    command: ["/root/command/armv-rec.sh"]


  actpp-train:
    <<: [*common, *gpu]
    container_name: koch-actpp-actpp-train
  

  actpp-deploy:
    <<: [*common, *gpu]
    container_name: koch-actpp-actpp-deploy