#############################
###    shared settings    ###
#############################
x-common-settings: &common
  tty: true
  network_mode: host
  privileged: true
  stop_grace_period: 1s
  devices:
    - /dev:/dev
  environment:
    - DISPLAY=${DISPLAY}
  

############################
###   shared settings    ###
############################
x-gpu-settings: &gpu
  runtime: nvidia
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]


############################
###   shared settings    ###
############################
x-workspace-settings: &workspace
  build: 
    context: .  
    dockerfile: Dockerfile
    target: release
  image: hrcnthu/kochact-rl:x86-gpu
  volumes:
    # GUI
    - $HOME/.Xauthority:/.Xauthority:ro
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
    # ROS2 container communication
    - /dev/shm:/dev/shm:rw
    # Udev rules 
    - /dev:/dev:rw
    - /run/udev:/run/udev:ro
    - /etc/udev:/etc/udev:ro

    # Workspace
    - ./entrypoint:/entrypoint
    - ../koch-lerobot:/koch-lerobot
    - ../ros2-ws/build:/ros2-ws/build
    - ../ros2-ws/install:/ros2-ws/install
    - ../ros2-ws/src:/ros2-ws/src
    # Note: you can comment out this line, 
    # if you don't need to upload dataset to huggingface.
    - ../.git/:/.git  # mount .git to setup the git credentials


##############################
###   Container Services   ###
##############################
services:
  raw:
    <<: [*common, *gpu, *workspace]
    container_name: raw
    command: ["/bin/bash"]

  build:
    <<: [*common, *gpu, *workspace]
    container_name: build
    entrypoint: ["/entrypoint/ws-build.sh"]

  cali:
    <<: [*common, *gpu, *workspace]
    container_name: cali
    entrypoint: ["/entrypoint/cali.sh"]

  teleop:
    <<: [*common, *gpu, *workspace]
    container_name: teleop
    entrypoint: ["/entrypoint/teleop.sh"]

  cam:
    <<: [*common, *gpu, *workspace]
    container_name: cam
    entrypoint: ["/entrypoint/cam.sh"]

  sync:
    <<: [*common, *gpu, *workspace]
    container_name: sync
    entrypoint: ["/entrypoint/sync.sh"]

  train:
    <<: [*common, *gpu, *workspace]
    container_name: train

  deploy:
    <<: [*common, *gpu, *workspace]
    container_name: deploy