#############################
###    shared settings    ###
#############################
x-common-settings: &common
  build: 
    context: .  
    dockerfile: Dockerfile
    target: release
  image: hrcnthu/lerobot-koch-actpp:gpu

  volumes:
    # GUI
    - $HOME/.Xauthority:/root/.Xauthority
    - /tmp/.X11-unix:/tmp/.X11-unix
    # ROS2 container communication
    - /dev/shm:/dev/shm
    # Udev rules 
    - /dev:/dev
    - /run/udev:/run/udev:ro
    - /etc/udev:/etc/udev:ro

    # workspace 
    - ../entrypoint:/root/entrypoint
    - ../../lerobot:/root/lerobot
    - ../../ros2-ws/build:/root/ros2-ws/build
    - ../../ros2-ws/install:/root/ros2-ws/install
    - ../../ros2-ws/src:/root/ros2-ws/src


    ## NOTE: mount .git to setup the git credentials
    #  you can comment out this line, 
    #  if you don't need to upload dataset to huggingface.
    - ../../.git/:/root/.git
  tmpfs:
    - /root/ros2-ws/log
  
  environment:
    - DISPLAY=${DISPLAY}
  
  tty: true
  network_mode: host
  privileged: true
  stop_grace_period: 1s
  devices:
    - /dev:/dev


############################
###   shared settings    ###
############################
x-gpu-settings: &gpu
  runtime: nvidia
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    

##############################
###   Container Services   ###
##############################
services:
  raw:
    <<: [*common, *gpu]
    container_name: koch-actpp-raw
    command: ["/bin/bash"]


  ws-build:
    <<: [*common, *gpu]
    container_name: koch-actpp-ws-build
    entrypoint: ["/bin/bash", "-c", 
                  "/root/entrypoint/symlinks.sh; /root/entrypoint/ws-build.sh"]


  arm-cali:
    <<: [*common, *gpu]
    container_name: koch-actpp-arm-cali
    entrypoint: ["/bin/bash", "-c", 
                  "/root/entrypoint/symlinks.sh; /root/entrypoint/arm-cali.sh"]

  arm-sync:
    <<: [*common, *gpu]
    container_name: koch-actpp-arm-sync
    entrypoint: ["/bin/bash", "-c", 
                  "/root/entrypoint/symlinks.sh; /root/entrypoint/arm-sync.sh"]

  
  armv-rec:
    <<: [*common, *gpu]
    container_name: koch-actpp-armv-rec
    entrypoint: ["/bin/bash", "-c", 
                  "/root/entrypoint/symlinks.sh", "/root/entrypoint/armv-rec.sh"]


  actpp-train:
    <<: [*common, *gpu]
    container_name: koch-actpp-actpp-train
  

  actpp-deploy:
    <<: [*common, *gpu]
    container_name: koch-actpp-actpp-deploy